language: python
python:
  - "2.7"
    #  - "3.3"
    #- "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
    - export AIRFLOW_GPL_UNIDECODE=yes
    - pip install -e . 
    - pip install --upgrade Flask
    - pip install python-daemon==2.1.2
    - python setup.py build -v && python setup.py install
script:
  - py.test #--cov-report term-missing --cov app -v

